INSERT INTO PERSON VALUES (1, '2000-01-01', 'Taras', 'Stepanov', true);
INSERT INTO PERSON VALUES (2, '1990-02-12', 'Ivan', 'Sidorov', true);
INSERT INTO PERSON VALUES (3, '1995-03-13', 'Petr', 'Kolobkov', true);
INSERT INTO PERSON VALUES (4, '1998-04-16', 'Fedor', 'Ignatov', true);
INSERT INTO PERSON VALUES (5, '1997-05-20', 'Maxim', 'Ivanov', true);
INSERT INTO PERSON VALUES (6, '1996-02-21', 'Artyom', 'Krutov', false);
INSERT INTO PERSON VALUES (7, '1986-03-25', 'Kirill', 'Sinitsa', true);
INSERT INTO PERSON VALUES (8, '1980-04-03', 'Roman', 'Dyvo', true);
INSERT INTO PERSON VALUES (9, '1995-09-12', 'Alexandr', 'Loshak', true);

INSERT INTO MANAGER VALUES (1, 8, true);
INSERT INTO MANAGER VALUES (2, 9, false);

INSERT INTO CLIENT_LEVEL_TYPE VALUES (1, 'Applicant', true, 'APL');
INSERT INTO CLIENT_LEVEL_TYPE VALUES (2, 'Beginner', true, 'BGN');
INSERT INTO CLIENT_LEVEL_TYPE VALUES (3, 'Regular', true, 'REG');
INSERT INTO CLIENT_LEVEL_TYPE VALUES (4, 'Graduate', true, 'GRD');

INSERT INTO CLIENT_STATUS_TYPE VALUES (1, 'Active', true, 'ACT');
INSERT INTO CLIENT_STATUS_TYPE VALUES (2, 'Frozen', true, 'FRZ');
INSERT INTO CLIENT_STATUS_TYPE VALUES (3, 'Pending', true, 'PND');

INSERT INTO CLIENT VALUES (1, 1, null, 1, null, true);
INSERT INTO CLIENT VALUES (2, 2, 1, 2, 1, true);
INSERT INTO CLIENT VALUES (3, 2, 2, 3, 1, true);
INSERT INTO CLIENT VALUES (4, 2, 2, 4, 1, true);
INSERT INTO CLIENT VALUES (5, 2, 2, 5, 2, true);
INSERT INTO CLIENT VALUES (6, 3, 1, 6, 1, true);
INSERT INTO CLIENT VALUES (7, 4, 1, 7, 1, true);

INSERT INTO CLIENT_STATUS_HISTORY VALUES (1, '2017-04-10', 5, 1, true);
INSERT INTO CLIENT_STATUS_HISTORY VALUES (2, '2017-04-15', 5, 2, true);
INSERT INTO CLIENT_STATUS_HISTORY VALUES (3, '2017-01-10', 1, 1, true);
INSERT INTO CLIENT_STATUS_HISTORY VALUES (4, '2017-02-15', 1, 2, true);
INSERT INTO CLIENT_STATUS_HISTORY VALUES (5, '2017-03-18', 1, 1, true);

INSERT INTO CONTACT_TYPE VALUES (1, 'telephone', true, 'phone');
INSERT INTO CONTACT_TYPE VALUES (2, 'e-mail', true, 'mail');
INSERT INTO CONTACT_TYPE VALUES (3, 'site', true, 'site');
INSERT INTO CONTACT_TYPE VALUES (4, 'skype', true, 'skype');
INSERT INTO CONTACT_TYPE VALUES (5, 'city', true, 'city');

INSERT INTO CONTACT VALUES (1, '0503265566', 1, 1, true);
INSERT INTO CONTACT VALUES (2, 'test@gmail.com', 2, 1, true);
INSERT INTO CONTACT VALUES (3, 'www.test.ua', 3, 1, true);
INSERT INTO CONTACT VALUES (4, 'testik', 4, 1, true);
INSERT INTO CONTACT VALUES (5, 'Kyev', 1, 1, true);
INSERT INTO CONTACT VALUES (6, '0936854214', 1, 2, true);
INSERT INTO CONTACT VALUES (7, 'karamba@gmail.com', 2, 2, true);
INSERT INTO CONTACT VALUES (8, null, 3, 2, true);
INSERT INTO CONTACT VALUES (9, 'rocket56', 4, 2, true);
INSERT INTO CONTACT VALUES (10, 'Kyev', 5, 2, true);